# Generated by Django 4.2.5 on 2023-09-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carrot_app', '0002_remove_chatmessage_sender_remove_chatroom_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='buyer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='buyer_chat_room', to=settings.AUTH_USER_MODEL),
        ),
    ]
