# Generated by Django 4.2.5 on 2023-10-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0004_remove_chatmessage_user_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardarea',
            name='city_id',
            field=models.IntegerField(null=True),
        ),
    ]
