# Generated by Django 4.2.5 on 2023-10-04 15:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0005_alter_standardarea_city_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='refreshed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
