# Generated by Django 4.2.5 on 2023-10-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0008_chatroom_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product_id',
            new_name='product',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='wish_list',
            field=models.ManyToManyField(blank=True, to='carrot_app.wishlist'),
        ),
    ]
