# Generated by Django 4.2.5 on 2023-10-05 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrot_app', '0009_rename_product_id_wishlist_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_liked_by_user',
            field=models.BooleanField(default=False),
        ),
    ]
